#!/bin/bash
reset
FILE=red-lights.txt
[ "$1" == "" ] || FILE="$1"


while read LINE; do
    [ -n "$LINE" ] || continue
    RED "$LINE"

    ADJ=''
    echo $LINE | grep -qc 'between'
    ret=$?

    if [ $ret != 0 ]; then

        # simple red light camera is just a 'point'
        POINT1_LHS=`echo $LINE | cut -d'&' -f1 | cut -d'/' -f1 | cut -d'(' -f1`
        POINT1_RHS=`echo $LINE | cut -d'&' -f2 | cut -d'/' -f1 | cut -d'(' -f1`

        if [ "$POINT1_LHS" == "$POINT1_RHS" ]; then
            
            # did not find an ampersand. re-parse
    
            # it says xyz meters from some street
            # 1 ) POINT1_LHS is everything to the left of the first NUMBER found.
            # 2 ) POINT1_RHS is everythine after the word 'of'
            # 3 ) adjust is everythine not above
    
            POINT1_LHS=`echo $LINE | sed 's=.[0-9].*=='`
            #set -x
            POINT1_RHS=`echo $LINE | rev | sed 's=.fo .*==' | rev `  # fo is a rev 'of'
            ADJ=`echo $LINE | sed "s=$POINT1_LHS==" | sed "s=$POINT1_RHS=="`
            #set +x
        else
            POINT1_RHS=`echo $POINT1_RHS | cut -c1-`
        fi

        GREEN "LHS=$POINT1_LHS"
        CYAN "RHS=$POINT1_RHS"
        YELLOW "ADJ=$ADJ"

        ./intersection2GPS "$POINT1_LHS" "$POINT1_RHS"
   
    else
        # string contained the word "between"
        # three coords - on road X between avenue Y and street Z
        COMMON_POINT=`echo $LINE | sed 's= between.*=='`

        POINT1_RHS=`echo $LINE | rev | sed 's= dna.*==' | rev`

        POINT1_LHS=`echo $LINE | sed "s=$COMMON_POINT==" | sed "s=$POINT1_RHS==" | sed 's= between ==' | sed 's= and =='`

        GREEN "COMMON=$COMMON_POINT"
        CYAN "LHS=$POINT1_LHS"
        CYAN "RHS=$POINT1_RHS"
 
        ./intersection2GPS "$COMMON_POINT" "$POINT1_LHS"
        ./intersection2GPS "$COMMON_POINT" "$POINT1_RHS"
    fi



    echo "-------------------------------" >&2

done < $FILE

